### PR TITLE
Felipe fix api spec

### PR DESCRIPTION
**Pull request by fcoralsasso**
This PR covers the issues on https://github.com/CanDIG/htsget_app/issues/85

### CODE REVIEW

**Comment by ljdursi** [comment]
Looks good so far - wha needs to happen to get the tests working?  A first issue is that those ?id=... urls should be /id?referenceName=..

**Comment by shaikh-rashid** [comment]
Looks good, our implementation is based on an outdated spec so this needed to be addressed. Please resolve tests and bump the release version in setup.py.

**Review by ljdursi — APPROVED** [review]
Looks good to me!

**Review by shaikh-rashid — APPROVED** [review]
Lgtm

**Review by jimmyhli — APPROVED** [review]

**Pull request merged**
