### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by daisieh**
I don't have jira tickets for these, but while working on DIG-910, I found some other problems in htsget:

* multiple region search now works
* better error handling for when htsget can't find a file for a drs_object
* the data endpoints were performing incorrectly:
  - the variants/{id} endpoint should return an array of variants/data/{id} URLs that, concatenated together, constitute a VCF file. Minimally, header + body should be returned as separate URLs.
  - search now returns a property "htsget" which contains the same sort of HTSGetURL object specified in openapi.yml.

Pytest should still work correctly and you should be able to see the new formats in the Paw request for variant search:
* from CanDIGv2, python settings.py, source env.sh, export TESTENV_URL=http://docker.localhost:3333
* cd lib/htsget-server
* pip install -r requirements.txt
* cd htsget_app
* pytest
* go to Paw and run the "add items to dataset" request to add the test objects to a dataset user1 can see
* run the variant search request

### CODE REVIEW

**Comment by daisieh** [comment]
(travis is failing but I think it's because of weird quirks with the minio sandbox: it is not consistently affecting all files, which is annoying)

**Comment by SonQBChau** [comment]
It didn't pass the tests, not sure if I missed something in the instructions.
```
============================================================== test session starts ===============================================================
platform linux -- Python 3.10.4, pytest-7.2.0, pluggy-1.0.0
rootdir: /app/htsget_server
collected 24 items                                                                                                                               

tests/test_htsget_server.py .FFFFFF..FFFFFF.FFFFFFFF                                                                                       [100%]

==================================================================== FAILURES ====================================================================
_______________________________________________________________ test_post_objects ________________________________________________________________

drs_objects = [{'aliases': [], 'checksums': [], 'created_time': '2021-09-27T18:40:00.538843', 'description': '', ...}, {'aliases': [...gz.tbi'], 'id': 'index', 'name': 'multisample_1.vcf.gz.tbi'}], 'created_time': '2021-09-27T18:40:00.538843', ...}, ...]

    def test_post_objects(drs_objects):
        """
        Install test objects. Will fail if any post request returns an error.
        """
        # clean up old objects in db:
        url = f"{HOST}/ga4gh/drs/v1/objects"
        headers = get_headers()
        response = requests.request("GET", url, headers=headers)
    
        client = None
    
        try:
            bucket = 'testhtsget'
            if MINIO_URL and VAULT_URL and MINIO_ACCESS_KEY and MINIO_SECRET_KEY:
                token = get_access_token(username=USERNAME, password=PASSWORD)
>               credential, status_code = store_aws_credential(token=token, endpoint=MINIO_URL, bucket=bucket, access=MINIO_ACCESS_KEY, secret=MINIO_SECRET_KEY, vault_url=VAULT_URL)
E               TypeError: store_aws_credential() got an unexpected keyword argument 'token'

tests/test_htsget_server.py:59: TypeError
```
I did run pytest with the previous version and it is fine

**Comment by daisieh** [comment]
I bet you have an old version of candigv2-authx in there...run pip uninstall candigv2-authx first, then build and compose as before. You'll have to sit through the rebuild of pysam, sorry!

**Review by SonQBChau — APPROVED** [review]
LGTM

**Comment by kcranston** [comment]
I don't want to hold this up because of my local testing woes. I've looked through the code, and assuming that this has been tested in dev in the context of the stack, I am ok to merge. 

One question - why the codefactor test failure? Is this test important? should we keep it?

**Comment by SonQBChau** [comment]
You can click on details and it will tell you. Pretty minor thing, like linting fix

**Pull request merged**
